spring.application.name=mssc-inventory-service
logging.level.guru=debug
server.port=8082

spring.artemis.user=artemis
spring.artemis.password=artemis

logging.level.guru.sfg=debug

# Cattura il 100% dei passaggi (utilizza valori piu' bassi come 0.05 o 0.10 in produzione)
management.tracing.sampling.probability=1.0

# Endpoint del tuo raccoglitore di tracce (es. Jaeger, Tempo, OpenObserve)
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
