spring.application.name=mssc-inventory-service
logging.level.guru=debug
server.port=8082

spring.artemis.user=artemis
spring.artemis.password=artemis

logging.level.guru.sfg=debug

# 1. Disabilita completamente l'esportatore di tracce OpenTelemetry
management.otlp.metrics.export.enabled=false

# 2. Imposta la probabilita' di campionamento a 0 (nessuna traccia viene catturata)
management.tracing.sampling.probability=0.0

spring.security.user.name=good
spring.security.user.password=beer